### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by sandcore-dev** [jacobdekeizer/ccvshop-client#19]
With the list of endpoints growing larger, I think the memory usage of the client is going to be an issue eventually.

Currently, the `Client` constructor creates instances for all endpoint classes:

```php
    public function __construct()
    {
        $this->client = new HttpClient();
        $this->rootEndpoint = new Endpoints\RootEndpoint($this);
        $this->appsEndpoint = new Endpoints\AppsEndpoint($this);
        // and so forth
    }
```

But it's very likely only one or two endpoints are going to be used, so that's a lot of endpoint instances unused. Since the endpoints are only accessible by getters, it would be better to create the instance there:

```php
    public function products(): Endpoints\ProductsEndpoint
    {
        if ($this->productsEndpoint === null) {
                $this->productsEndpoint = new Endpoints\ProductsEndpoint($this);
        }

        return $this->productsEndpoint;
    }
```

**Comment by jacobdekeizer** [comment]
Hi @sandcore-dev,

Yeah I was planning on removing the endpoint properties entirely, and just return the new endpoint directly.

**Comment by jacobdekeizer** [comment]
@sandcore-dev I've removed the endpoint properties, see v0.16.0.
